import { useEffect, useState, type ReactElement } from "react";
import Head from "next/head";
import {
  Hero,
  TechStack,
  ExperiencePage,
  CitationOverlay,
} from "@/components/pages";
import { Container, Navbar } from "@/components/ui";
import { userData } from "@/constants";
import { motion } from "framer-motion";
export default function Home() {
  const { headTitle } = userData;
  const [citation, setCitation] = useState(true);
  const [main, setMain] = useState(false);

  useEffect(() => {
    const ids = [
      setTimeout(() => setCitation(false), 4800),
      setTimeout(() => setMain(true), 5700),
    ];
    return () => ids.forEach((id) => clearTimeout(id));
  }, [setCitation]);

  return (
    <>
      <Head>
        <title>{headTitle}</title>
        <meta name="description" content="Generated by Create Next Stack." />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700&family=Roboto+Flex:opsz,wght@8..144,400;8..144,700;8..144,900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <CitationOverlay citation={citation} />
      <motion.div
        variants={{
          initial: {
            opacity: 0,
            display: "none",
          },
          visible: {
            opacity: 1,
            display: "block",
          },
        }}
        initial="initial"
        animate={main ? "visible" : "initial"}
        transition={{
          duration: 1.0,
        }}
      >
        <Navbar />
        <Hero />
        <TechStack />
        <ExperiencePage />
      </motion.div>
    </>
  );
}
