import type { ReactElement } from "react";
import Head from "next/head";
import { Hero, TechStack } from "components";
import WebsiteLayout from "../components/Layout/website";
import { userData } from "../constants";
export default function Home() {
  const { headTitle } = userData;

  return (
    <>
      <Head>
        <title>{headTitle}</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <Hero />
      <TechStack />
    </>
  );
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <WebsiteLayout>{page}</WebsiteLayout>;
};
