import { Hero, CitationOverlay } from "components";
import { motion } from "framer-motion";
import { GetStaticProps } from "next";
import Head from "next/head";
// import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import React, { useEffect, useState } from "react";

const Index = () => {
  const [citation, setCitation] = useState(true);
  const [main, setMain] = useState(false);
  const { t } = useTranslation("common");

  useEffect(() => {
    const ids = [
      setTimeout(() => setCitation(false), 4800),
      setTimeout(() => setMain(true), 5700),
    ];
    return () => ids.forEach((id) => clearTimeout(id));
  }, [setCitation]);

  return (
    <>
      <Head>
        <title>timdehof.dev</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <CitationOverlay citation={citation} />
      <motion.div
        variants={{
          initial: {
            opacity: 0,
            display: "none",
          },
          visible: {
            opacity: 1,
            display: "block",
          },
        }}
        initial="initial"
        animate={main ? "visible" : "initial"}
        transition={{
          duration: 1.0,
        }}
      >
        <Hero />
      </motion.div>
      {/* <LandingPageTemplate /> */}
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "en", ["common"])),
    },
  };
};

export default Index;
